version: '3.4'

services:
  mcfwebsite:
    image: mcfwebsite
    build:
      context: client
      dockerfile: ./Dockerfile
    init: true
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    restart: unless-stopped
